### ISSUE TITLE
Segfault at end of Intro

### ISSUE THREAD

**Issue by Voytella** [TheEntireCommunistManifesto/OpenRCT2#4]
OS: Debian Sid
Version: 0.0.7
Commit/Build: 2e37d6e (build+commit)

The program segfaults if I leave the intro to play uninterrupted, after the RCT logo fades. This does not happen when I stop the intro by clicking or pressing any key.

**Steps to reproduce:**

1. Start OpenRCT normally, with intro turned on
2. Leave the intro to play, without clicking/pressing any key until the RCT logo fades out

Link to Original: https://github.com/OpenRCT2/OpenRCT2/issues/5288

**Comment by mwilmott2013** [comment]
The issue seems to be related to the screaming audio channel self-deleting when it finishes, but it can't because the sound-channel is deleted by the audio-mixer before it can finish.  The obvious fix would be to change the screaming audio channel self-delete bit (the boolean true) to false, and then there will not be a case of deleting something that isn't there.  Except since my efforts have not been able to even get the intro to even play, there is no way to test this fix.  Hopefully, we can find a way soon...

**Comment by Voytella** [comment]
The problem was in L. 111 of '/Sources/intro.c'. '_soundChannel' was being assigned to the output of the function 'Mixer_Play_Effect'. One of the parameters being passed into the function was 'true', and changing it to 'false' fixed the issue.
